#ifndef BASE64_ALPHABET_H
#define BASE64_ALPHABET_H

//struct character {
//    uint8_t data:6;
//};

enum characters {
    ALBT_A,
    ALBT_B,
    ALBT_C,
    ALBT_D,
    ALBT_E,
    ALBT_F,
    ALBT_G,
    ALBT_H,
    ALBT_I,
    ALBT_J,
    ALBT_K,
    ALBT_L,
    ALBT_M,
    ALBT_N,
    ALBT_O,
    ALBT_P,
    ALBT_Q,
    ALBT_R,
    ALBT_S,
    ALBT_T,
    ALBT_U,
    ALBT_V,
    ALBT_W,
    ALBT_X,
    ALBT_Y,
    ALBT_Z,
    ALBT_a,
    ALBT_b,
    ALBT_c,
    ALBT_d,
    ALBT_e,
    ALBT_f,
    ALBT_g,
    ALBT_h,
    ALBT_i,
    ALBT_j,
    ALBT_k,
    ALBT_l,
    ALBT_m,
    ALBT_n,
    ALBT_o,
    ALBT_p,
    ALBT_q,
    ALBT_r,
    ALBT_s,
    ALBT_t,
    ALBT_u,
    ALBT_v,
    ALBT_w,
    ALBT_x,
    ALBT_y,
    ALBT_z,
    ALBT_0,
    ALBT_1,
    ALBT_2,
    ALBT_3,
    ALBT_4,
    ALBT_5,
    ALBT_6,
    ALBT_7,
    ALBT_8,
    ALBT_9,
    ALBT_PLUS,
    ALBT_SLASH,
};

char alphabet[64] = {
        [ALBT_A] = 'A',
        [ALBT_B] = 'B',
        [ALBT_C] = 'C',
        [ALBT_D] = 'D',
        [ALBT_E] = 'E',
        [ALBT_F] = 'F',
        [ALBT_G] = 'G',
        [ALBT_H] = 'H',
        [ALBT_I] = 'I',
        [ALBT_J] = 'J',
        [ALBT_K] = 'K',
        [ALBT_L] = 'L',
        [ALBT_M] = 'M',
        [ALBT_N] = 'N',
        [ALBT_O] = 'O',
        [ALBT_P] = 'P',
        [ALBT_Q] = 'Q',
        [ALBT_R] = 'R',
        [ALBT_S] = 'S',
        [ALBT_T] = 'T',
        [ALBT_U] = 'U',
        [ALBT_V] = 'V',
        [ALBT_W] = 'W',
        [ALBT_X] = 'X',
        [ALBT_Y] = 'Y',
        [ALBT_Z] = 'Z',
        [ALBT_a] = 'a',
        [ALBT_b] = 'b',
        [ALBT_c] = 'c',
        [ALBT_d] = 'd',
        [ALBT_e] = 'e',
        [ALBT_f] = 'f',
        [ALBT_g] = 'g',
        [ALBT_h] = 'h',
        [ALBT_i] = 'i',
        [ALBT_j] = 'j',
        [ALBT_k] = 'k',
        [ALBT_l] = 'l',
        [ALBT_m] = 'm',
        [ALBT_n] = 'n',
        [ALBT_o] = 'o',
        [ALBT_p] = 'p',
        [ALBT_q] = 'q',
        [ALBT_r] = 'r',
        [ALBT_s] = 's',
        [ALBT_t] = 't',
        [ALBT_u] = 'u',
        [ALBT_v] = 'v',
        [ALBT_w] = 'w',
        [ALBT_x] = 'x',
        [ALBT_y] = 'y',
        [ALBT_z] = 'z',
        [ALBT_0] = '0',
        [ALBT_1] = '1',
        [ALBT_2] = '2',
        [ALBT_3] = '3',
        [ALBT_4] = '4',
        [ALBT_5] = '5',
        [ALBT_6] = '6',
        [ALBT_7] = '7',
        [ALBT_8] = '8',
        [ALBT_9] = '9',
        [ALBT_PLUS] = '+',
        [ALBT_SLASH] = '=',
};

#endif //BASE64_ALPHABET_H
